import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import { ReactNode, StrictMode } from 'react'

const nunito = Nunito({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Find a Friend',
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <StrictMode>
      <html lang="pt-BR" className={nunito.className}>
        <body>{children}</body>
      </html>
    </StrictMode>
  )
}
